! Parameters -------------------------------
aH = pars_b(1,:)
nHB = pars_b(2,:)
nHC = pars_b(3,:)
aV = pars_b(4,:)
nVB = pars_b(5,:)
nVH = pars_b(6,:)
nVBH = pars_b(7,:)
aK = pars_b(8,:)
nKB = pars_b(9,:)
nKH = pars_b(10,:)
nKC = pars_b(11,:)
nKrh = pars_b(12,:)
aHL = pars_b(13,:)
nHLB = pars_b(14,:)
nHLL = pars_b(15,:)
nHLC = pars_b(16,:)
nHLrh = pars_b(17,:)
! Weibull parsameters ---
Dscale0 = pars_b(18,:)
DscaleB = pars_b(19,:)
Dscalerh = pars_b(20,:)
Dscalet = pars_b(21,:)
DscaleC = pars_b(22,:)

Dshape0 = pars_b(23,:)
DshapeB = pars_b(24,:)
Dshaperh = pars_b(25,:)
Dshapet = pars_b(26,:)
DshapeC = pars_b(27,:)

Dlocation0 = pars_b(28,:)
DlocationB = pars_b(29,:)
Dlocationrh = pars_b(30,:)
Dlocationt = pars_b(31,:)
DlocationC = pars_b(32,:)

wsscale0 = pars_b(33,:)
wsscaleB = pars_b(34,:)
wsscalerh = pars_b(35,:)
wsscalet = pars_b(36,:)
wsscaleC = pars_b(37,:)

wsshape0 = pars_b(38,:)
wsshapeB = pars_b(39,:)
wsshaperh = pars_b(40,:)
wsshapet = pars_b(41,:)
wsshapeC = pars_b(42,:)

wslocation0 = pars_b(43,:)
wslocationB = pars_b(44,:)
wslocationrh = pars_b(45,:)
wslocationt = pars_b(46,:)
wslocationC = pars_b(47,:)