! Reading the mapin input 
! Structure
! Group
!   - site; species; climate; parameters
! Inputs are ordered by the order they are provided for the program
! Other variables are ordered by group and alphabeticaly


! Site data ----------------------------
lat         = siteInputs(1)
soil_class  = int( siteInputs(2) )
aSW         = siteInputs(3)
asw_min     = siteInputs(4)
asw_max     = siteInputs(5)
year_i      = int( siteInputs(6) )
month_i     = int( siteInputs(7) )
altitude    = int( siteInputs(8) )


! Species data -------------------------
year_p      = int( speciesInputs(:,2) )
month_p     = int( speciesInputs(:,3) )
fertility   = speciesInputs(:,4)
biom_foliage_i = speciesInputs(:,5)
biom_root_i = speciesInputs(:,6)
biom_stem_i = speciesInputs(:,7)
stems_n_i   = speciesInputs(:,8)


! Climate ------------------------------
tmp_min     = forcingInputs(:,1)
tmp_max     = forcingInputs(:,2)
prcp        = forcingInputs(:,3)
solar_rad   = forcingInputs(:,4)
frost_days  = forcingInputs(:,5)
co2         = forcingInputs(:,6)


! Parameters ---------------------------
pFS2        = parameterInputs(1,:)
pFS20       = parameterInputs(2,:)
aWs         = parameterInputs(3,:)
nWs         = parameterInputs(4,:)
pRx         = parameterInputs(5,:)
pRn         = parameterInputs(6,:)
gammaF1     = parameterInputs(7,:)
gammaF0     = parameterInputs(8,:)
tgammaF     = parameterInputs(9,:)
gammaR      = parameterInputs(10,:)
leafgrow    = int( parameterInputs(11,:) )
leaffall    = int( parameterInputs(12,:) )
Tmin        = parameterInputs(13,:)
Topt        = parameterInputs(14,:)
Tmax        = parameterInputs(15,:)
kF          = parameterInputs(16,:)
SWconst0    = parameterInputs(17,:)
SWpower0    = parameterInputs(18,:)
fCalpha700  = parameterInputs(19,:)
fCg700      = parameterInputs(20,:)
m0          = parameterInputs(21,:)
fN0         = parameterInputs(22,:)
fNn         = parameterInputs(23,:)
MaxAge      = parameterInputs(24,:)
nAge        = parameterInputs(25,:)
rAge        = parameterInputs(26,:)
gammaN1     = parameterInputs(27,:)
gammaN0     = parameterInputs(28,:)
tgammaN     = parameterInputs(29,:)
ngammaN     = parameterInputs(30,:)
wSx1000     = parameterInputs(31,:)
thinPower   = parameterInputs(32,:)
mF          = parameterInputs(33,:)
mR          = parameterInputs(34,:)
mS          = parameterInputs(35,:)
SLA0        = parameterInputs(36,:)
SLA1        = parameterInputs(37,:)
tSLA        = parameterInputs(38,:)
k           = parameterInputs(39,:)
fullCanAge  = parameterInputs(40,:)
MaxIntcptn  = parameterInputs(41,:)
LAImaxIntcptn = parameterInputs(42,:)
cVPD        = parameterInputs(43,:)
alphaCx     = parameterInputs(44,:)
y           = parameterInputs(45,:)
MinCond     = parameterInputs(46,:)
MaxCond     = parameterInputs(47,:)
LAIgcx      = parameterInputs(48,:)
CoeffCond   = parameterInputs(49,:)
BLcond      = parameterInputs(50,:)
RGcGW       = parameterInputs(51,:)
D13CTissueDif = parameterInputs(52,:)
aFracDiffu  = parameterInputs(53,:)
bFracRubi   = parameterInputs(54,:)
fracBB0     = parameterInputs(55,:)
fracBB1     = parameterInputs(56,:)
tBB         = parameterInputs(57,:)
rho0        = parameterInputs(58,:)
rho1        = parameterInputs(59,:)
tRho        = parameterInputs(60,:)
CrownShape  = int( parameterInputs(61,:) )